"""revision3

Revision ID: 0d47b0418da3
Revises: 87cc3aa3f3ec
Create Date: 2020-01-10 15:50:35.017001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d47b0418da3'
down_revision = '87cc3aa3f3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
