"""revision6

Revision ID: 24e06bfe5a07
Revises: e66e821a0d28
Create Date: 2020-01-10 17:35:19.689017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e06bfe5a07'
down_revision = 'e66e821a0d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
