"""four

Revision ID: 7bab4d15480c
Revises: e175e0f4ebf9
Create Date: 2020-01-09 20:30:55.738167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bab4d15480c'
down_revision = 'e175e0f4ebf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
