"""revision2

Revision ID: 87cc3aa3f3ec
Revises: 91f222d37c31
Create Date: 2020-01-10 15:49:17.314576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87cc3aa3f3ec'
down_revision = '91f222d37c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seo_moduloconfiguracion', 'estado',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seo_moduloconfiguracion', 'estado',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###
