"""second

Revision ID: b6cab4aeacc4
Revises: 685232bad991
Create Date: 2020-01-09 19:21:06.347630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6cab4aeacc4'
down_revision = '685232bad991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('seo_administrador', sa.Column('password', sa.String(), nullable=True))
    # op.drop_column('seo_administrador', 'pass')
    # op.add_column('seo_usuario', sa.Column('password', sa.String(), nullable=True))
    # op.drop_column('seo_usuario', 'pass')
    # ### end Alembic commands ###

    op.alter_column('seo_administrador','pass', new_column_name='password', nullable=True,existing_type=mysql.CHAR(length=255))
    op.alter_column('seo_usuario','pass', new_column_name='password', nullable=True,existing_type=mysql.CHAR(length=255))


def downgrade():
    pass
