"""third

Revision ID: e175e0f4ebf9
Revises: b6cab4aeacc4
Create Date: 2020-01-09 19:23:15.541143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e175e0f4ebf9'
down_revision = 'b6cab4aeacc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
