"""revision7

Revision ID: e21d163adfd8
Revises: 24e06bfe5a07
Create Date: 2020-01-10 17:45:06.444125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21d163adfd8'
down_revision = '24e06bfe5a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
