"""revision5

Revision ID: e66e821a0d28
Revises: bff852faadf7
Create Date: 2020-01-10 17:06:07.352710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66e821a0d28'
down_revision = 'bff852faadf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
