"""added field in images

Revision ID: fc1b5b475aff
Revises: e21d163adfd8
Create Date: 2020-02-20 12:09:33.889800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc1b5b475aff'
down_revision = 'e21d163adfd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seo_administrador', 'foto')
    op.drop_column('seo_banner', 'foto')
    op.drop_column('seo_galeria', 'foto')
    op.add_column('seo_image', sa.Column('field_name', sa.String(length=255), nullable=True))
    op.drop_column('seo_logo', 'foto')
    op.drop_column('seo_pedidoproducto', 'foto')
    op.drop_column('seo_producto', 'foto')
    op.drop_column('seo_productocategoria', 'foto')
    op.drop_column('seo_seccion', 'foto')
    op.drop_column('seo_seccioncategoria', 'foto')
    op.drop_column('seo_seo', 'foto')
    op.drop_column('seo_seo', 'banner')
    op.drop_column('seo_usuario', 'foto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seo_usuario', sa.Column('foto', mysql.LONGTEXT(), nullable=True))
    op.add_column('seo_seo', sa.Column('banner', mysql.LONGTEXT(), nullable=True))
    op.add_column('seo_seo', sa.Column('foto', mysql.LONGTEXT(), nullable=True))
    op.add_column('seo_seccioncategoria', sa.Column('foto', mysql.LONGTEXT(), nullable=True))
    op.add_column('seo_seccion', sa.Column('foto', mysql.LONGTEXT(), nullable=True))
    op.add_column('seo_productocategoria', sa.Column('foto', mysql.LONGTEXT(), nullable=True))
    op.add_column('seo_producto', sa.Column('foto', mysql.LONGTEXT(), nullable=True))
    op.add_column('seo_pedidoproducto', sa.Column('foto', mysql.CHAR(length=255), nullable=True))
    op.add_column('seo_logo', sa.Column('foto', mysql.LONGTEXT(), nullable=True))
    op.drop_column('seo_image', 'field_name')
    op.add_column('seo_galeria', sa.Column('foto', mysql.LONGTEXT(), nullable=True))
    op.add_column('seo_banner', sa.Column('foto', mysql.LONGTEXT(), nullable=True))
    op.add_column('seo_administrador', sa.Column('foto', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###
